/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { medium_pathname$_T } from './medium_pathname$_b.js'
import type { medium_pathname_a$_T } from './medium_pathname_a$_b.js'
import type { medium_pathname_idx$_T } from './medium_pathname_idx$_b.js'
import type { source_medium_pathname_a$_T } from './source_medium_pathname_a$_b.js'
export interface instagram_cache_ctx_I {
	medium_pathname$?:medium_pathname$_T
	medium_pathname_a$?:medium_pathname_a$_T
	medium_pathname_idx$?:medium_pathname_idx$_T
	source_medium_pathname_a$?:source_medium_pathname_a$_T
}